### ISSUE TITLE
Visualization in a Jupyter notebook does not show, notebook raises ZMQ and tornado errors

### ISSUE THREAD

**Issue by antalszava** [qc-design/plaquette#43]
### Maybe it's already fixed?

- [X] I tried the latest version available on PyPI.
- [X] Same problem occurs on `main` branch.

### Describe the bug

Running plaquette code that calls on visualization tools like `draw_lattice` has not been showing any images in a Jupyter notebook. In the terminal, the notebook raised ZMQ and tornado errors, while in the browser the executed cell in the notebook simply didn't show anything.

### Expected behavior

An image appears in the notebook after executing a cell that contains drawing logic.

### Minimal Working Example

```python
import numpy as np
import plaquette
from plaquette.codes import LatticeCode
from plaquette import visualizer

repetition_code = LatticeCode.make_repetition(size=3, n_rounds=1)

vis = visualizer.LatticeVisualizer(repetition_code)
vis.draw_lattice(height=300)
```

### Traceback (if any)

```Python traceback
[E 10:15:22.324 NotebookApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/home/anaconda3/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/home/anaconda3/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/home/anaconda3/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/home/anaconda3/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 334, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 1081, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 1056, in _write_frame
        return self.stream.write(frame)
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/iostream.py", line 539, in write
        self._handle_write()
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/iostream.py", line 965, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[E 10:15:22.325 NotebookApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/home/anaconda3/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 634, in _handle_events
        self._handle_recv()
      File "/home/anaconda3/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 663, in _handle_recv
        self._run_callback(callback, msg)
      File "/home/anaconda3/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/home/anaconda3/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/home/anaconda3/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/home/anaconda3/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 334, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 1081, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 1056, in _write_frame
        return self.stream.write(frame)
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/iostream.py", line 539, in write
        self._handle_write()
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/iostream.py", line 965, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[E 10:15:22.326 NotebookApp] Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7f3b8e2db1c0>)
    Traceback (most recent call last):
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/ioloop.py", line 738, in _run_callback
        ret = callback()
      File "/home/anaconda3/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 718, in <lambda>
        self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
      File "/home/anaconda3/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 634, in _handle_events
        self._handle_recv()
      File "/home/anaconda3/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 663, in _handle_recv
        self._run_callback(callback, msg)
      File "/home/anaconda3/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/home/anaconda3/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/home/anaconda3/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/home/anaconda3/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 334, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 1081, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 1056, in _write_frame
        return self.stream.write(frame)
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/iostream.py", line 539, in write
        self._handle_write()
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/iostream.py", line 965, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/home/anaconda3/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
```

### Version

PyPI

**Comment by antalszava** [comment]
Note that this has been an error coming up for some time and the error could be narrowed down simply to creating a `Figure` from plotly.
```py
import plotly.graph_objects as go
go.Figure()
```
This yielded the same behaviour.

Today, upgrading `plotly` and `notebook` via
```
pip install plotly --upgrade
pip install notebook --upgrade 
```
solved the issue and with `plotly==5.17.0` and with `notebook==7.0.4` the issue is resolved.
