### ISSUE TITLE
Visualizer AssertionError in quickstart.py

### ISSUE THREAD

**Issue by mattsantand** [qc-design/plaquette#81]
### Maybe it's already fixed?

- [X] I tried the latest version available on PyPI.
- [X] Same problem occurs on `main` branch.

### Describe the bug

In a new environment I installed the current main branch of plaquette (version 0.0.1a3). No error raised during installation.
Tried to run the `quickstart.py` (in PyCharm). 
The decoding was successful but I got an AssertionError regarding the visualizer

### Traceback (if any)

```Python traceback
Traceback (most recent call last):
  File "C:\Users\matte\Documents\QCDesign\pythonProject\plaquette\examples\quickstart.py", line 53, in <module>
    fig = visualizer.draw_latticedata(
  File "C:\Users\matte\Documents\QCDesign\pythonProject\plaquette\venv\lib\site-packages\plaquette\visualizer\__init__.py", line 449, in draw_latticedata
    vdf = pd.concat((vdf, self._mk_pauliframe_df(error, correction, only_pauli)))
  File "C:\Users\matte\Documents\QCDesign\pythonProject\plaquette\venv\lib\site-packages\plaquette\visualizer\__init__.py", line 180, in _mk_pauliframe_df
    assert corr is None or len(corr) == 1
AssertionError
```

### Version

main branch

**Comment by massarom** [comment]
This should be fixed already in #77. Can you check if this happens still in that PR/branch?
