### ISSUE TITLE
IndexError in example files

### ISSUE THREAD

**Issue by mattsantand** [qc-design/plaquette#84]
### Maybe it's already fixed?

- [X] I tried the latest version available on PyPI.
- [X] Same problem occurs on `main` branch.

### Describe the bug

In a new environment I installed the current main branch of plaquette (version 0.0.1a3). No error raised during installation.
Tried to run the example file `ler_decreases.py` (in PyCharm).
I got the following error

### Traceback (if any)

```Python traceback
Traceback (most recent call last):
  File "XXXXXXXX\plaquette\examples\ler_decreases.py", line 66, in <module>
    results = MeasurementSample.from_code_and_raw_results(ssc, raw, erasure, num_rounds)
  File "XXXXXXXX\plaquette\venv\lib\site-packages\plaquette\device\__init__.py", line 114, in from_code_and_raw_results
    logop_wts = [code.distances[j] for j in logop_idxs]
  File "XXXXXXXX\plaquette\venv\lib\site-packages\plaquette\device\__init__.py", line 114, in <listcomp>
    logop_wts = [code.distances[j] for j in logop_idxs]
IndexError: index 2 is out of bounds for axis 0 with size 2
```

### Version

main branch

**Comment by massarom** [comment]
This should be fixed by #76, does it still happen there?
